"""add user role

Revision ID: 13424cd947b2
Revises: 9a0296d1a75c
Create Date: 2022-04-02 22:30:30.069910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '13424cd947b2'
down_revision = '9a0296d1a75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = postgresql.ENUM('super_admin', 'admin', 'user', name="user_role")
    user_role.create(op.get_bind())
    op.add_column('clothes', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='user_role'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'role')
    # ### end Alembic commands ###
