"""add user role

Revision ID: 38ca06192cc8
Revises: 13424cd947b2
Create Date: 2022-04-02 22:57:57.625013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38ca06192cc8'
down_revision = '13424cd947b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = postgresql.ENUM('super_admin', 'admin', 'user', name="user_role")
    user_role.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='user_role'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('clothes', sa.Column('role', postgresql.ENUM('super_admin', 'admin', 'user', name='user_role'), server_default=sa.text("'user'::user_role"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
