"""add user role

Revision ID: b0a356ef6e2b
Revises: 38ca06192cc8
Create Date: 2022-04-02 23:02:11.280511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0a356ef6e2b'
down_revision = '38ca06192cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('role', postgresql.ENUM('super_admin', 'admin', 'user', name='user_role'), server_default=sa.text("'user'::user_role"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
